language: node_js
node_js:
  - "node"
install:
  - npm install
before_script:
  - npm install -g now
script:
  - npm run lint
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deployserver
